version: '3.2'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=.env(DB_NAME)
      - POSTGRES_USER=.env(DB_USER)
      - POSTGRES_PASSWORD=.env(DB_PASSWORD)
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
